### ISSUE TITLE
How to upgrade version?

### ISSUE THREAD

**Issue by adrenaline96** [clamwin/clamav-win32#1]
Hello,

Currently freshclam doesn't upgrade the installation version. Say you are on 0.99.2 and 0.99.3 is released, it will warn you that your version is outdated, but it doesn't update it by itself.

Is there any possibility to upgrade the existing version to the newest one via command lines or something? Or do we need to reinstall the files?

**Comment by clamwin** [comment]
freshclam only updates virus definitions, to update antivirus itself you need to get new packages if you use standalone version or follow the link on clamwin gui when it offers to update, right now clamwin 0.99.4 is in test
