### ISSUE TITLE
0.103.4

### ISSUE THREAD

**Issue by RvdHout** [clamwin/clamav-win32#11]
Hey sherpya, how are you doing?

I am aware ClamAV 0.104.x is released that includes your 'fixes' to run it as a service.
Unfortunately am am not able to use 0.104.x (yet) as there seem some compatibility issues with 0.103.x and 0.104.x, especially concerning spamd.exe and the way it responds to a stream, if you are interested you can read more about this incompatibility here:
https://www.hmailserver.com/forum/viewtopic.php?f=7&t=37507
https://github.com/hmailserver/hmailserver/blob/master/hmailserver/source/Server/Common/AntiVirus/ClamAVVirusScanner.cpp#L71

In the meanwhile would it be possible for you to push a 0.103.4 release?

**Comment by sherpya** [comment]
I've released 0.103.4, I suspect merging the 0.104 version would be a little difficult

**Comment by RvdHout** [comment]
Hello sherpya,
Thx for the update, one thing i noticed in 0.103.4 vs previous packages in 0.103.x range is libclamav.lib is missing in the archive (all seems to be running fine though, so not sure if this is a issue at all)

FYI, i was not asking for you to merge 0.104... i hoped maybe you could tell why feeding a stream to clamd no longer works with 0.104, i browsed through the clamav changelog but couldn't find any reference to changes made there.  With 0.104 it returns UNKNOWN COMMAND where 0.103.4 would return PORT {with random port nr}

**Comment by sherpya** [comment]
@RvdHout sorry I changed a bit cmakefile and forgot to ship lib file, I've updated the 7z, same name
