### ISSUE TITLE
clamscan.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by Forusim** [clamwin/clamav-win32#2]
Hello,
i get the following error: 
The procedure entry point _ftime64 could not be located in the dynamic link library msvcrt.dll.

Here is my system information:

Build: clamav-mingw-0.99.4.7z
System: Windows NT 4.0 SP6a
Internet Explorer: 5.0
msvcrt.dll: 6.00.8797.0

~~According to my research the function "_ftime64" should be included in the msvcrt.dll version 6.00.8797.0~~
Edit: Checked with Notepad++ the contents of the above dll and didn´t found any "_ftime64".

**Comment by clamwin** [comment]
Just tested on NT4 4.00.1381 ENU IE 5 6.0.2800.1106, my crt is somehow newer 6.10.8637.0
You can try to download a new one e.g. from here [http://www.mdgx.com/wnt4.htm](http://www.mdgx.com/wnt4.htm)

**Comment by Forusim** [comment]
I tried to place your version in the same directory as clamscan.exe, but same error.

I was not able to replace in E:\WINNT\system32, because it is used by many windows processes.

Is there somehow a way to include the crt, so it will work on any system?

I have attached the version from my Win NT4 machine:
[MSVCRT.zip](https://github.com/clamwin/clamav-win32/files/1917176/MSVCRT.zip)

**Comment by Forusim** [comment]
It looks like some other applikation, e.g. IE 6 has updated your msvcrt.dll.
I have checked with Notepad++ the contents of your version and found the function "_ftime64".

However I cannot change any dlls on system, i will have to scan with this portable? tool.

Looking forward for a solution. Thanks.

**Comment by sherpya** [comment]
unfortunately msvcrt is marked as system dll and putting in the executable directory just does not work, I don't use it directly, it's used by pthreads win32, I need to see I can redirect to a custom implementation and if there are other missing imports

**Comment by sherpya** [comment]
Hi, I've made a new mingw build (updated 0.100.0) it does not use anymore ftime64

**Comment by Forusim** [comment]
Works perfectly, thanks a lot!
