### ISSUE TITLE
freshclam.exe exit code 1 on Database is up-to-date

### ISSUE THREAD

**Issue by Forusim** [clamwin/clamav-win32#4]
Hello,

using the freshclam.exe in batch I try to capture some errors.

According to https://www.systutorials.com/docs/linux/man/1-freshclam/ the exit code on "Database is up-to-date" should be 0, but with the version 0.100.0 I receive exit code 1.

Is this a bug or a feature?

**Comment by sherpya** [comment]
You may call it feature :) please look at https://github.com/clamwin/clamav/blob/0.100.1/freshclam/freshclamcodes.h `FC_UPTODATE` is 1

**Comment by batmat** [comment]
Hello, sorry just stumbled into here after looking for the same error reason, and reading the docs telling me 

> 0 : Database is up\-to\-date or successfully updated.

https://github.com/clamwin/clamav/blob/8de125e48b51b691155a542ba0c25c4b9b9cb5e0/docs/man/freshclam.1.in#L100

Is this just that `freshclam` manpage is outdated, or I'm missing something?

Thanks!

**Comment by jvshahid** [comment]
Ping.  We ran into the same issue.  Not sure why `1` was chosen for successful database update.  Is it possible to change this to `0` and be consistent with the man page ?

**Comment by radiolondra** [comment]
I'm stuck with new freshclam version 101. With version 100 everything was fine in updates. Now, after an update, even if I delete the whole database from the database folder freshclam says always "Database is up-to-date or successfully updated". Bah? Where are the databases? Is Freshclam still looking at the freshclam.conf or something is changed?
