### ISSUE TITLE
Clamd x64-0.103.0 service stuck on "Starting"

### ISSUE THREAD

**Issue by magl8** [clamwin/clamav-win32#8]
On two Windows servers, we have the issue that the Clamd.exe service of version x64-0.103.0 never starts completely but stays on "Starting" in services.msc.
However, the service is available and the clamd.log seems OK, the regular SelfChecks are also logged correctly.
The prolonged status of "Starting" led to some alarms from our monitoring solution, this is why I noticed.
I already re-installed VC-Runtimes and restarted the servers, which did not change the service status.

Here is the conf file:
TCPAddr 127.0.0.1
TCPSocket 3310
MaxThreads 40
LogFileMaxSize 20480000
LogTime true
LogFile c:\Clamav\log\clamd.log
DatabaseDirectory c:\clamav\db
TemporaryDirectory c:\clamav\tmp
PhishingScanURLs no
ScanArchive no
ScanMail no

And here is the log:
Fri Nov 13 13:04:01 2020 -> +++ Started at Fri Nov 13 13:04:01 2020
Fri Nov 13 13:04:01 2020 -> Received 0 file descriptor(s) from systemd.
Fri Nov 13 13:04:01 2020 -> clamd daemon 0.103.0 (OS: win32, ARCH: x86_64, CPU: x86_64)
Fri Nov 13 13:04:01 2020 -> Log file size limited to 20480000 bytes.
Fri Nov 13 13:04:01 2020 -> Reading databases from c:\clamav\db
Fri Nov 13 13:04:01 2020 -> Not loading PUA signatures.
Fri Nov 13 13:04:01 2020 -> Bytecode: Security mode set to "TrustSigned".
Fri Nov 13 13:04:01 2020 -> Disabling URL based phishing detection.
Fri Nov 13 13:05:31 2020 -> Loaded 9292081 signatures.
Fri Nov 13 13:05:37 2020 -> TCP: Bound to [127.0.0.1]:3310
Fri Nov 13 13:05:37 2020 -> TCP: Setting connection queue length to 200
Fri Nov 13 13:05:37 2020 -> Limits: Global time limit set to 120000 milliseconds.
Fri Nov 13 13:05:37 2020 -> Limits: Global size limit set to 104857600 bytes.
Fri Nov 13 13:05:37 2020 -> Limits: File size limit set to 26214400 bytes.
Fri Nov 13 13:05:37 2020 -> Limits: Recursion level limit set to 16.
Fri Nov 13 13:05:37 2020 -> Limits: Files limit set to 10000.
Fri Nov 13 13:05:37 2020 -> Limits: MaxEmbeddedPE limit set to 10485760 bytes.
Fri Nov 13 13:05:37 2020 -> Limits: MaxHTMLNormalize limit set to 10485760 bytes.
Fri Nov 13 13:05:37 2020 -> Limits: MaxHTMLNoTags limit set to 2097152 bytes.
Fri Nov 13 13:05:37 2020 -> Limits: MaxScriptNormalize limit set to 5242880 bytes.
Fri Nov 13 13:05:37 2020 -> Limits: MaxZipTypeRcg limit set to 1048576 bytes.
Fri Nov 13 13:05:37 2020 -> Limits: MaxPartitions limit set to 50.
Fri Nov 13 13:05:37 2020 -> Limits: MaxIconsPE limit set to 100.
Fri Nov 13 13:05:37 2020 -> Limits: MaxRecHWP3 limit set to 16.
Fri Nov 13 13:05:37 2020 -> Limits: PCREMatchLimit limit set to 100000.
Fri Nov 13 13:05:37 2020 -> Limits: PCRERecMatchLimit limit set to 2000.
Fri Nov 13 13:05:37 2020 -> Limits: PCREMaxFileSize limit set to 26214400.
Fri Nov 13 13:05:37 2020 -> Archive support disabled.
Fri Nov 13 13:05:37 2020 -> AlertExceedsMax heuristic detection disabled.
Fri Nov 13 13:05:37 2020 -> Heuristic alerts enabled.
Fri Nov 13 13:05:37 2020 -> Portable Executable support enabled.
Fri Nov 13 13:05:37 2020 -> ELF support enabled.
Fri Nov 13 13:05:37 2020 -> Mail files support disabled.
Fri Nov 13 13:05:37 2020 -> OLE2 support enabled.
Fri Nov 13 13:05:37 2020 -> PDF support enabled.
Fri Nov 13 13:05:37 2020 -> SWF support enabled.
Fri Nov 13 13:05:37 2020 -> HTML support enabled.
Fri Nov 13 13:05:37 2020 -> XMLDOCS support enabled.
Fri Nov 13 13:05:37 2020 -> HWP3 support enabled.
Fri Nov 13 13:05:37 2020 -> Self checking every 600 seconds.
Fri Nov 13 13:15:37 2020 -> SelfCheck: Database status OK.

**Comment by pik-256** [comment]
The same on Windows 2012 Server. Clamd v. x64-0.103.0.

Log:
Sat Nov 21 18:46:29 2020 -> +++ Started at Sat Nov 21 18:46:29 2020
Sat Nov 21 18:46:29 2020 -> Received 0 file descriptor(s) from systemd.
Sat Nov 21 18:46:29 2020 -> clamd daemon 0.103.0 (OS: win32, ARCH: x86_64, CPU: x86_64)
Sat Nov 21 18:46:29 2020 -> Log file size limited to 1048576 bytes.
Sat Nov 21 18:46:29 2020 -> Reading databases from c:\ProgramData\ClamAV
Sat Nov 21 18:46:29 2020 -> Not loading PUA signatures.
Sat Nov 21 18:46:29 2020 -> Bytecode: Security mode set to "TrustSigned".
Sat Nov 21 18:46:52 2020 -> Loaded 9052403 signatures.
Sat Nov 21 18:46:58 2020 -> TCP: Bound to [127.0.0.1]:3310
Sat Nov 21 18:46:58 2020 -> TCP: Setting connection queue length to 200
Sat Nov 21 18:46:58 2020 -> Limits: Global time limit set to 120000 milliseconds.
Sat Nov 21 18:46:58 2020 -> Limits: Global size limit set to 104857600 bytes.
Sat Nov 21 18:46:58 2020 -> Limits: File size limit set to 26214400 bytes.
Sat Nov 21 18:46:58 2020 -> Limits: Recursion level limit set to 10.
Sat Nov 21 18:46:58 2020 -> Limits: Files limit set to 10000.
Sat Nov 21 18:46:58 2020 -> Limits: MaxEmbeddedPE limit set to 10485760 bytes.
Sat Nov 21 18:46:58 2020 -> Limits: MaxHTMLNormalize limit set to 10485760 bytes.
Sat Nov 21 18:46:58 2020 -> Limits: MaxHTMLNoTags limit set to 2097152 bytes.
Sat Nov 21 18:46:58 2020 -> Limits: MaxScriptNormalize limit set to 5242880 bytes.
Sat Nov 21 18:46:58 2020 -> Limits: MaxZipTypeRcg limit set to 1048576 bytes.
Sat Nov 21 18:46:58 2020 -> Limits: MaxPartitions limit set to 50.
Sat Nov 21 18:46:58 2020 -> Limits: MaxIconsPE limit set to 100.
Sat Nov 21 18:46:58 2020 -> Limits: MaxRecHWP3 limit set to 16.
Sat Nov 21 18:46:58 2020 -> Limits: PCREMatchLimit limit set to 100000.
Sat Nov 21 18:46:58 2020 -> Limits: PCRERecMatchLimit limit set to 2000.
Sat Nov 21 18:46:58 2020 -> Limits: PCREMaxFileSize limit set to 26214400.
Sat Nov 21 18:46:58 2020 -> Archive support enabled.
Sat Nov 21 18:46:58 2020 -> AlertExceedsMax heuristic detection disabled.
Sat Nov 21 18:46:58 2020 -> Heuristic alerts enabled.
Sat Nov 21 18:46:58 2020 -> Portable Executable support enabled.
Sat Nov 21 18:46:58 2020 -> ELF support enabled.
Sat Nov 21 18:46:58 2020 -> Mail files support enabled.
Sat Nov 21 18:46:58 2020 -> OLE2 support enabled.
Sat Nov 21 18:46:58 2020 -> PDF support enabled.
Sat Nov 21 18:46:58 2020 -> SWF support enabled.
Sat Nov 21 18:46:58 2020 -> HTML support enabled.
Sat Nov 21 18:46:58 2020 -> XMLDOCS support enabled.
Sat Nov 21 18:46:58 2020 -> HWP3 support enabled.
Sat Nov 21 18:46:58 2020 -> Self checking disabled.
Sat Nov 21 18:46:58 2020 -> Listening daemon: PID: 4112
Sat Nov 21 18:46:58 2020 -> MaxQueue set to: 100

Clamd runs and behaves properly, except a service status.

**Comment by sherpya** [comment]
It should be fixed in 0.103.0-r1
