### ISSUE TITLE
can't update anymore

### ISSUE THREAD

**Issue by kosuodhmwa** [clamwin/clamav-win32#9]
![cw](https://user-images.githubusercontent.com/24782840/110608057-2456b980-818c-11eb-939c-8456bf92ce0a.JPG)

Thank you very much for your feedbacks...

**Comment by kosuodhmwa** [comment]
oh it was the wrong picture...

![cw2](https://user-images.githubusercontent.com/24782840/110608278-62ec7400-818c-11eb-8954-a64440f42f48.JPG)

**Comment by sawyerit** [comment]
I'm having a similar issue.... 

PS C:\clamav> .\freshclam --verbose
Current working dir is C:\clamav\db
Max retries == 3
ClamAV update process started at Fri Mar 12 04:39:45 2021
Using IPv6 aware code
TTL: 531
Software version from DNS: 0.103.1
Retrieving http://database.clamav.net/main.cvd
Trying to download http://database.clamav.net/main.cvd (IP: 104.16.218.84)
WARNING: getfile: Unknown response from remote server (IP: 104.16.218.84)
WARNING: Can't download main.cvd from database.clamav.net
Trying again in 5 secs...
ClamAV update process started at Fri Mar 12 04:39:50 2021
Using IPv6 aware code
TTL: 526
Software version from DNS: 0.103.1
Retrieving http://database.clamav.net/main.cvd
Trying to download http://database.clamav.net/main.cvd (IP: 104.16.218.84)
WARNING: getfile: Unknown response from remote server (IP: 104.16.218.84)
WARNING: Can't download main.cvd from database.clamav.net
Trying again in 5 secs...

**Comment by kosuodhmwa** [comment]
-> That works: https://github.com/clamwin/clamwin/issues/2#issuecomment-796820666
